// Second floor (400x240 display), same footprint as page0.
// Top bedroom spans the full width (155,6 to 295,63). Below it, the
// corridor is a vertical strip (155,63 to 205,233, 50 wide x 170
// tall) reaching the other 3 bedrooms, stacked on the right
// (205,63 to 295,233), each opening into the corridor through its
// own door. Each bedroom has one window. The staircase is the same
// module as on page0, but opens into the corridor at its top end.
// Door and window gaps stay open here. Small door_N and window_N text
// components cover them, and the firmware colors them white (closed) or
// red (open).

// Outer top wall, split for the top bedroom's window (210 to 240)
line 155,6,210,6,65535
line 240,6,295,6,65535

// Outer right wall, split for a window in each of the 3 lower
// bedrooms (B: 80-100, C: 135-155, D: 195-215)
line 295,6,295,63,65535
line 295,63,295,80,65535
line 295,100,295,119,65535
line 295,119,295,135,65535
line 295,155,295,176,65535
line 295,176,295,195,65535
line 295,215,295,233,65535

// Outer bottom wall (corridor + bottom bedroom, solid, no exterior
// door on this floor)
line 155,233,295,233,65535

// Corridor outer left wall, split for the staircase opening (63 to 113)
line 155,6,155,63,65535
line 155,113,155,233,65535

// Top bedroom / corridor dividing wall (y=63), split for its door
// (170 to 182). Right side (205 to 295) is solid: bedroom B doesn't
// connect directly to the top bedroom, only via the corridor.
line 155,63,170,63,65535
line 182,63,205,63,65535
line 205,63,295,63,65535

// Bedroom / corridor dividing wall (x=205), split for the 3 lower
// bedroom doors (B: 85-97, C: 141-153, D: 198-210)
line 205,63,205,85,65535
line 205,97,205,141,65535
line 205,153,205,198,65535
line 205,210,205,233,65535

// Bedroom / bedroom dividing walls (solid, rooms don't connect to each other)
line 205,119,295,119,65535
line 205,176,295,176,65535

// Staircase module, a 50x150 box bumped out to the left of the corridor
// (105,63 to 155,213), the same on both floors. Its right side is the
// corridor wall. It opens into the corridor at the bottom (163 to 213)
// on the ground floor and at the top (63 to 113) on the second floor.
// Each opening is as tall as the box is wide, so the first step is
// flush with both walls.
line 105,63,155,63,65535
line 105,63,105,213,65535
line 105,213,155,213,65535

// Stair treads, generated by stairs.py. Both ends turn a quarter
// toward the corridor, with the winders fanning out in 15 degree steps
// from the inner corner (155,113 at the top, 155,163 at the bottom).
// The treads between the two turns are straight.
line 155,113,142,63,65535
line 155,113,126,63,65535
line 155,113,105,63,65535
line 155,113,105,84,65535
line 155,113,105,100,65535
line 155,113,105,113,65535
line 155,123,105,123,65535
line 155,133,105,133,65535
line 155,143,105,143,65535
line 155,153,105,153,65535
line 155,163,105,163,65535
line 155,163,105,176,65535
line 155,163,105,192,65535
line 155,163,105,213,65535
line 155,163,126,213,65535
line 155,163,142,213,65535
