[package]
edition      = "2024"
name         = "screen"
rust-version = "1.88"
version      = "0.1.0"

[dependencies]
esp-hal = { version = "~1.1.0", features = ["esp32", "unstable"] }

esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32"] }

esp-alloc = "0.10.0"
esp-backtrace = { version = "0.19.0", features = [
  "esp32",
  "panic-handler",
  "println",
] }
esp-println = { version = "0.17.0", features = ["esp32"] }
