// House outline (400x240 display), centered on screen.
// Corridor is a vertical strip (155,126 to 205,233, 50 wide x 107 tall,
// 33% taller than before). Living room is an L: long arm vertical
// (205,6 to 295,233, full height), short arm horizontal, sitting on
// top of the corridor (155,6 to 205,126).
// Staircase is a separate module bumped out to the left of the
// corridor, open into it at its bottom end.
// Door and window gaps stay open here. Small door_N and window_N text
// components cover them, and the firmware colors them white (closed) or
// red (open).

// Outer top wall (spans the living room's short arm and long arm),
// split for a window (210 to 240)
line 155,6,210,6,65535
line 240,6,295,6,65535
// Outer right wall (living room's long arm), split for a window (100 to 130)
line 295,6,295,100,65535
line 295,130,295,233,65535

// Outer bottom wall, split for the main entrance door gap
line 155,233,160,233,65535
line 190,233,295,233,65535

// Corridor outer left wall, split for the staircase opening (163 to 213)
line 155,6,155,163,65535
line 155,213,155,233,65535

// Corridor / living room dividing walls, split for a door (167 to 191)
line 155,126,205,126,65535
line 205,126,205,167,65535
line 205,191,205,233,65535

// Staircase module, a 50x150 box bumped out to the left of the corridor
// (105,63 to 155,213), the same on both floors. Its right side is the
// corridor wall. It opens into the corridor at the bottom (163 to 213)
// on the ground floor and at the top (63 to 113) on the second floor.
// Each opening is as tall as the box is wide, so the first step is
// flush with both walls.
line 105,63,155,63,65535
line 105,63,105,213,65535
line 105,213,155,213,65535

// Stair treads, generated by stairs.py. Both ends turn a quarter
// toward the corridor, with the winders fanning out in 15 degree steps
// from the inner corner (155,113 at the top, 155,163 at the bottom).
// The treads between the two turns are straight.
line 155,113,142,63,65535
line 155,113,126,63,65535
line 155,113,105,63,65535
line 155,113,105,84,65535
line 155,113,105,100,65535
line 155,113,105,113,65535
line 155,123,105,123,65535
line 155,133,105,133,65535
line 155,143,105,143,65535
line 155,153,105,153,65535
line 155,163,105,163,65535
line 155,163,105,176,65535
line 155,163,105,192,65535
line 155,163,105,213,65535
line 155,163,126,213,65535
line 155,163,142,213,65535
